<a href="https://colab.research.google.com/github/gopikasj2001-jpg/numpy1/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#wap to find the length of each word in a given list.
l=["apple","orange","mango"]
# for i in l:
#   print(len(i))
lst=[len(i) for i in l]
lst
import numpy as np
# help(np)

In [ ]:
print("Hello World")

Hello World


In [ ]:
l=[1,2,3,4]
z=np.array(l)
# z
print(z)

[1 2 3 4]


In [ ]:
l=[1,2.0,3,4]
z=np.array(l)
print(z)

[1. 2. 3. 4.]


In [ ]:
l=[1,2,3,"4"]
z=np.array(l)
print(z)

['1' '2' '3' '4']


In [ ]:
import numpy as np
l=[1,2,3,4,5]
z=np.array(l)
print(z)

[1 2 3 4 5]


In [ ]:
z[4]
z[2:]
z[-2]
z[-3:]
z[-1:-4:-1]
z[-1: :-1]
z.ndim# to find the dimension
z.size# no.oof elements
z.shape# no.of rows and columns

In [ ]:
z=np.array([[1,2],[4,5]])
z
z.size
z.shape
z.ndim

2

In [ ]:
z=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])#tensors
z
z.shape#2 rows 2 columns 2 matrices
z.ndim
z.size

8

In [ ]:
z=np.array([[1,2,3],[4,5,6]])
z.shape

(2, 3)

In [ ]:
#4*2
z=np.array([[1,2],[3,4],[5,6],[7,8]])
z
z.shape

(4, 2)

In [ ]:
#4*4
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
z
z[2,2]
z[1,1]
z[1,2:]
z[1:3,1:3]
z[0:3,1:3]
z[1:,1:]
z[0:,0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [ ]:
#zero matrix
z=np.zeros([2,2,2],dtype=int)
# z=np.zeros([2,2],dtype=complex)
print(z)
z.ndim
z.shape
z.size


[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


8

In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
z

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
#create two 2*2 matrix
a=np.array([[1,2],[3,4]])
a
b=np.array([[5,6],[7,6]])
b
a+b
a-b
a/b
a*b# not matrix multiplication
a@b# for matrix multiplication
a.dot(b)#""

array([[19, 18],
       [43, 42]])

In [ ]:
#full matrix
z=np.full([2,2],4)
print(z)
z=np.full([2,2,3],2)
print(z)

[[4 4]
 [4 4]]
[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


In [ ]:
import numpy as np
#Identity matrix
#square matrix and diagonals whose positions w r t rows index and columns index should be same. eg:(1,1),(2,2),(3,3)
a=np.eye(4,dtype=int)
print(a)


[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
b=np.identity(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
#create a 3x3 matrix
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
a.shape
z=a.reshape(1,9)
print(z)
a=np.array([[1,2,3,4],[2,4,6,8],[1,2,8,5],[5,4,7,8]])
print(a)
a.reshape(8,2)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3 4 5 6 7 8 9]]
[[1 2 3 4]
 [2 4 6 8]
 [1 2 8 5]
 [5 4 7 8]]


array([[1, 2],
       [3, 4],
       [2, 4],
       [6, 8],
       [1, 2],
       [8, 5],
       [5, 4],
       [7, 8]])

In [13]:
# list(range(1,10))
# arange==>used in array to create a consecutive number of elements
#syntax==>arange(start,stop,step)
b=np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix without using np.array
z=np.arange(1,11).reshape(5,2)
z


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix with float values
z=np.array([[1.2,2.3,1.3],[2.1,3.4,5.1],[1.1,2.4,6.1]])
z
z=np.arange(1,10,dtype=float).reshape(3,3)
z

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
#floor
c=np.floor(z)
c

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
#ceil
d=np.ceil(z)
d

array([[2., 3., 2.],
       [3., 4., 6.],
       [2., 3., 7.]])

In [ ]:
#round-- closest even no:
z=np.array([[1.2,2.3,1.5],[2.1,3.4,5.5],[1.1,2.4,6.1]])
z
e=np.round(z)
print(z)
e

[[1.2 2.3 1.5]
 [2.1 3.4 5.5]
 [1.1 2.4 6.1]]


array([[1., 2., 2.],
       [2., 3., 6.],
       [1., 2., 6.]])

In [ ]:
#create a 3x3 matrix
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
z
z.max()
z.max(axis=1)#represent the rows max
z.max(axis=0)#represents the column max
z.min()
z.min(axis=1)
z.min(axis=0)
z.sum()
z.sum(axis=1)
z.sum(axis=0)

#In Pandas we have axis=1 for columns and axis=0 for rows.

array([12, 15, 18])

In [ ]:
np.sqrt(z)
np.sin(z)
np.cos(z)
np.tan(z)


array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [ ]:
#flatten--used to bring any dimensional values to one dimensional.
z.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#sort
z=np.array([[1.2,2.3,1.3],[2.1,3.4,5.1],[1.1,2.4,6.1]])
z
print(z)
print(np.sort(z))

[[1.2 2.3 1.3]
 [2.1 3.4 5.1]
 [1.1 2.4 6.1]]
[[1.2 1.3 2.3]
 [2.1 3.4 5.1]
 [1.1 2.4 6.1]]


In [ ]:
z=np.array([[1,4,2],[2,1,6],[2,8,4]])
print(z)
print(np.sort(z,axis=1))
print(np.argsort(z,axis=1))
print(np.argmax(z,axis=1))

[[1 4 2]
 [2 1 6]
 [2 8 4]]
[[1 2 4]
 [1 2 6]
 [2 4 8]]
[[0 2 1]
 [1 0 2]
 [0 2 1]]
[1 2 1]


In [ ]:
#create a 1d array with values 0-9




import numpy as np
z=np.arange(0,10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#create a 2d array of zeros with shape 3,4
z=np.zeros([3,4],dtype=int)
print(z)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [ ]:
#array with values from 5 to 50 with step 5
z=np.arange(5,51,5)
z

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [ ]:
#identity matrix of size 4x4
z=np.eye(4)
print(z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#Given [[1,2,3],[4,5,6]] find the size,shape,number of dimensions
z=np.array([[1,2,3],[4,5,6]])
z.ndim
z.shape
z.size


6

In [ ]:
#create a 4x4 matrix:
#extract element at(1,2)
#first row
#second column
#sub array
z=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(z)
z[1,2]
z[0]
z[:,2]
z[2:3]
z[0:1]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([ 3,  7, 11, 15])

In [ ]:
#create two one dimension array:
#add the arrays
#multiply each element of first array by 3
#find the max and min element
a=np.array([1,2,3])
a
b=np.array([4,5,6])
b
a+b
a*3
a.dot(3)
a.max()
b.max()
a.min()
b.min()

np.int64(4)

In [ ]:
#create a 3x3 matrix with float values and floor, ceil, round.
z=np.array([[1.5,2.3,4.6],[1.4,2.5,6.6],[3.3,6.7,1.8]])
a=np.floor(z)
a
b=np.ceil(z)
b
c=np.round(z)
c

array([[2., 2., 5.],
       [1., 2., 7.],
       [3., 7., 2.]])

In [ ]:
#create a 1d array change the dimension to 2d of any shape
z=np.array([1,2,3,4])
z
a=z.reshape(2,2)
print(a)
a.ndim
a.shape

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 3d array and convert it to 1d
z=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(z)
z.ndim
z.size
z.reshape(1,12)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
#create a 3x3 matrix and sort based on index
z=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(z)
print(np.sort(z,axis=1))
print(np.argsort(z,axis=1))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [0 1 2]
 [0 1 2]]
